/**
 * Summary.
 *
 * Description. A layout is UI that is shared between routes. 
 *
 * @link https://nextjs.org/docs/app/api-reference/file-conventions/layout
 */

import '@/styles/globals.css'

import { Rubik } from "next/font/google";

const rubik = Rubik({
  weight: ["400", "500"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
